<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | Gestão de Expedientes</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body class="app-page dashboard-layout">
    <?php $activePage = 'dashboard'; $pageTitle = 'Dashboard'; require __DIR__ . '/partials/app-header.php'; ?>
        <main class="dashboard-shell"><div class="welcome-row"><div><p class="section-kicker">Visão geral</p><h1>Bom dia, <?= htmlspecialchars(strtok($user['full_name'], ' '), ENT_QUOTES, 'UTF-8') ?>.</h1><p class="muted">Acompanhe o movimento do sistema num só lugar.</p></div><time class="today-label" datetime="<?= date('Y-m-d') ?>"><?= date('d/m/Y') ?></time></div>
            <section class="stats-grid" aria-label="Resumo do sistema"><div class="stat-card accent-primary"><span>Total de expedientes</span><strong><?= $summary['total'] ?></strong><small>Registos no sistema</small></div><div class="stat-card"><span>Recebidos</span><strong><?= $summary['received'] ?></strong><small>Entrada inicial</small></div><div class="stat-card"><span>Em tramitação</span><strong><?= $summary['in_progress'] ?></strong><small>Em acompanhamento</small></div><div class="stat-card"><span>Aguardando despacho</span><strong><?= $summary['awaiting_dispatch'] ?></strong><small>Ação pendente</small></div><div class="stat-card"><span>Concluídos</span><strong><?= $summary['completed'] ?></strong><small>Prontos para arquivo</small></div><div class="stat-card"><span>Arquivados</span><strong><?= $summary['archived'] ?></strong><small>Histórico preservado</small></div><div class="stat-card"><span>Utilizadores ativos</span><strong><?= $summary['users'] ?></strong><small>Contas habilitadas</small></div></section>
            <div class="dashboard-columns"><section class="dashboard-panel activity-panel"><div class="panel-heading"><div><p class="section-kicker">Rastreabilidade</p><h2>Atividade recente</h2></div><?php if (hasPermission($connection, 'auditoria.view')): ?><a class="text-link" href="auditoria.php">Ver tudo</a><?php endif; ?></div><?php if ($recentActivity): ?><div class="activity-list"><?php foreach ($recentActivity as $activity): ?><div class="activity-row"><span class="activity-dot"></span><div><strong><?= htmlspecialchars($activity['action'], ENT_QUOTES, 'UTF-8') ?></strong><p><?= htmlspecialchars($activity['user_name'] ?? 'Sistema/Anónimo', ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars($activity['entity_type'], ENT_QUOTES, 'UTF-8') ?> #<?= (int) $activity['entity_id'] ?></p></div><time><?= htmlspecialchars(date('d/m H:i', strtotime($activity['created_at'])), ENT_QUOTES, 'UTF-8') ?></time></div><?php endforeach; ?></div><?php else: ?><div class="empty-state">Ainda não existem atividades registadas.</div><?php endif; ?></section><section class="dashboard-panel status-panel"><div class="panel-heading"><div><p class="section-kicker">Distribuição</p><h2>Estado dos expedientes</h2></div></div><?php $statusItems = [['received', 'Recebidos', '#2563A6'], ['in_progress', 'Em tramitação', '#F59E0B'], ['awaiting_dispatch', 'Aguardando despacho', '#D97706'], ['completed', 'Concluídos', '#16A34A'], ['archived', 'Arquivados', '#64748B']]; ?><div class="status-bars"><?php foreach ($statusItems as [$key, $label, $color]): ?><div class="status-bar-row"><div><span><?= $label ?></span><strong><?= $summary[$key] ?></strong></div><div class="progress-track"><i style="width: <?= $summary['total'] ? round(($summary[$key] / $summary['total']) * 100) : 0 ?>%; background: <?= $color ?>"></i></div></div><?php endforeach; ?></div></section></div>
            <section class="quick-actions"><p class="section-kicker">Acesso rápido</p><div><?php if (hasPermission($connection, 'expedientes.view')): ?><a href="expedientes.php">Expedientes <span>→</span></a><?php endif; ?><?php if (hasPermission($connection, 'tramitacoes.view')): ?><a href="tramitacoes.php">Tramitação <span>→</span></a><?php endif; ?><?php if (hasPermission($connection, 'despachos.view')): ?><a href="despachos.php">Despachos <span>→</span></a><?php endif; ?><?php if (hasPermission($connection, 'relatorios.view')): ?><a href="relatorios.php">Relatórios <span>→</span></a><?php endif; ?></div></section>
        </main>
    <?php require __DIR__ . '/partials/app-footer.php'; ?>
