<!DOCTYPE html>
<html lang="pt">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Expedientes | Gestão de Expedientes</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="app-page dashboard-layout">
<?php $activePage = 'expedientes'; $pageTitle = 'Expedientes'; require __DIR__ . '/partials/app-header.php'; ?>
<main class="content-shell">
    <div class="page-heading"><div><p class="section-kicker">Gestão documental</p><h1>Expedientes</h1><p class="muted">Registe e acompanhe os documentos administrativos.</p></div><?php if (hasPermission($connection, 'expedientes.manage')): ?><a class="primary-link" href="expediente-form.php">Novo expediente</a><?php endif; ?></div>
    <?php if ($message): ?><div class="flash <?= htmlspecialchars($message['type'], ENT_QUOTES, 'UTF-8') ?>" role="status"><?= htmlspecialchars($message['message'], ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
    <form class="search-bar" method="get" action="expedientes.php"><label for="search">Pesquisar por número, assunto, remetente, setor ou estado</label><div><input id="search" name="search" type="search" value="<?= htmlspecialchars($search, ENT_QUOTES, 'UTF-8') ?>" placeholder="Ex.: EXP-2026-001"><select name="status" aria-label="Filtrar por estado"><option value="">Todos os estados</option><?php foreach ($statuses as $key => $label): ?><option value="<?= htmlspecialchars($key, ENT_QUOTES, 'UTF-8') ?>" <?= $status === $key ? 'selected' : '' ?>><?= htmlspecialchars($label, ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select><button type="submit">Pesquisar</button></div></form>
    <section class="table-panel" aria-labelledby="expeditions-title"><div class="panel-heading"><h2 id="expeditions-title">Registos de expedientes</h2><span><?= count($expeditions) ?> resultado(s)</span></div><div class="table-wrap"><table><thead><tr><th>Número</th><th>Assunto</th><th>Origem / destino</th><th>Entrada</th><th>Estado</th><th>Ações</th></tr></thead><tbody>
    <?php foreach ($expeditions as $expedition): ?><tr><td><strong><?= htmlspecialchars($expedition['reference_code'], ENT_QUOTES, 'UTF-8') ?></strong></td><td><?= htmlspecialchars($expedition['subject'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($expedition['origin'], ENT_QUOTES, 'UTF-8') ?><br><span class="table-secondary">→ <?= htmlspecialchars($expedition['destination'], ENT_QUOTES, 'UTF-8') ?></span></td><td><?= htmlspecialchars(date('d/m/Y H:i', strtotime($expedition['received_at'])), ENT_QUOTES, 'UTF-8') ?></td><td><span class="state-badge state-<?= htmlspecialchars($expedition['status'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($statuses[$expedition['status']] ?? $expedition['status'], ENT_QUOTES, 'UTF-8') ?></span></td><td class="actions"><a href="expediente-view.php?id=<?= (int) $expedition['id'] ?>">Ver</a><?php if (hasPermission($connection, 'expedientes.manage')): ?><a href="expediente-form.php?id=<?= (int) $expedition['id'] ?>">Editar</a><?php endif; ?></td></tr><?php endforeach; ?>
    <?php if (!$expeditions): ?><tr><td colspan="6" class="empty-state">Nenhum expediente encontrado.</td></tr><?php endif; ?></tbody></table></div></section>
</main>
<?php require __DIR__ . '/partials/app-footer.php'; ?>