<!DOCTYPE html>
<html lang="pt">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Tramitação | Gestão de Expedientes</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="app-page dashboard-layout">
<?php $activePage = 'tramitacoes'; $pageTitle = 'Tramitação'; require __DIR__ . '/partials/app-header.php'; ?>
<main class="content-shell"><div class="page-heading"><div><p class="section-kicker">Fluxo documental</p><h1>Tramitação</h1><p class="muted">Acompanhe o percurso de cada expediente dentro da instituição.</p></div></div>
<?php if ($message): ?><div class="flash <?= htmlspecialchars($message['type'], ENT_QUOTES, 'UTF-8') ?>" role="status"><?= htmlspecialchars($message['message'], ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<?php if (!$selectedExpedition): ?><section class="table-panel"><div class="panel-heading"><h2>Selecione um expediente</h2><span><?= count($expeditions) ?> disponível(eis)</span></div><div class="table-wrap"><table><thead><tr><th>Número</th><th>Assunto</th><th>Estado</th><th>Ação</th></tr></thead><tbody><?php foreach ($expeditions as $expedition): ?><tr><td><strong><?= htmlspecialchars($expedition['reference_code'], ENT_QUOTES, 'UTF-8') ?></strong></td><td><?= htmlspecialchars($expedition['subject'], ENT_QUOTES, 'UTF-8') ?></td><td><span class="state-badge state-<?= htmlspecialchars($expedition['status'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars((new ExpeditionController())->getStatuses()[$expedition['status']] ?? $expedition['status'], ENT_QUOTES, 'UTF-8') ?></span></td><td><a class="table-link" href="tramitacoes.php?expediente_id=<?= (int) $expedition['id'] ?>">Abrir histórico</a></td></tr><?php endforeach; ?><?php if (!$expeditions): ?><tr><td colspan="4" class="empty-state">Ainda não existem expedientes.</td></tr><?php endif; ?></tbody></table></div></section>
<?php else: ?><div class="page-heading sub-heading"><div><p class="section-kicker">Expediente selecionado</p><h2><?= htmlspecialchars($selectedExpedition['reference_code'], ENT_QUOTES, 'UTF-8') ?></h2><p class="muted"><?= htmlspecialchars($selectedExpedition['subject'], ENT_QUOTES, 'UTF-8') ?></p></div><?php if (hasPermission($connection, 'tramitacoes.manage')): ?><a class="primary-link" href="tramitacao-form.php?expediente_id=<?= (int) $selectedExpedition['id'] ?>">Nova tramitação</a><?php endif; ?></div>
<section class="timeline-panel"><h2>Histórico completo</h2><?php if (!$history): ?><p class="empty-state">Ainda não existem tramitações para este expediente.</p><?php else: ?><ol class="timeline"><?php foreach ($history as $item): ?><li><div class="timeline-marker"></div><div class="timeline-content"><div class="timeline-heading"><strong><?= htmlspecialchars($item['destination'], ENT_QUOTES, 'UTF-8') ?></strong><span><?= htmlspecialchars(date('d/m/Y H:i', strtotime($item['sent_at'])), ENT_QUOTES, 'UTF-8') ?></span></div><p><strong>Origem:</strong> <?= htmlspecialchars($item['sender_name'] ?? 'Utilizador removido', ENT_QUOTES, 'UTF-8') ?></p><p><strong>Responsável:</strong> <?= htmlspecialchars($item['responsible_name'] ?? 'Utilizador removido', ENT_QUOTES, 'UTF-8') ?></p><?php if ($item['observation']): ?><p><strong>Observação:</strong> <?= nl2br(htmlspecialchars($item['observation'], ENT_QUOTES, 'UTF-8')) ?></p><?php endif; ?><span class="state-badge state-tram-<?= htmlspecialchars($item['status'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($statuses[$item['status']] ?? $item['status'], ENT_QUOTES, 'UTF-8') ?></span></div></li><?php endforeach; ?></ol><?php endif; ?></section><?php endif; ?></main></body></html>